// packages/solid-js/src/Storybook.jsx
import { For, createSignal, onCleanup, Show, Switch, Match } from 'solid-js'
import styles from './Storybook.module.css'

/**
 * @typedef {object} Story
 * @property {string} title
 * @property {() => JSX.Element} component
 */

const getLocationHash = () => decodeURIComponent(location.hash.substring(1))

/**
 * Tiny Storybook for solid-js
 * @param {object} props
 * @param {Story[] | HTMLElement[] | JSX.Element[]} props.stories stories
 * @param {string} [props.header='Storybook'] title
 * @param {string} [props.href='/'] header link
 * @param {number} [props.width=130] aside width
 * @returns {Node}
 */
export default function Storybook(props) {
  const stories = () => props.stories
  const header = () => props.header || 'Storybook Tiny'
  const href = () => props.href || '/stories/index.html'
  const width = () => props.width ?? 130

  const [active, setActive] = createSignal(getLocationHash())
  
  // define hash router
  const handleHashchange = () => {
    const hash = getLocationHash() 
    if (hash === '!') {
      window.location.hash = active()
      return
    }
    setActive(hash)
  }
  window.addEventListener('hashchange', handleHashchange)
  onCleanup(() => {
    window.removeEventListener('hashchange', handleHashchange)
  })

  return (
    <main class={styles.storybook}>
      <aside style={{ 'flex-basis': cssUnit(width()) }}>
        <h4>
          <a href={href()}>{header()}</a>
        </h4>
        <For each={stories()}>
          {(component) => (
            <Story component={component} active={active} />
          )}
        </For>
      </aside>
      <section>
        <Switch fallback={<DefaultStory />}>
          <Match when={active() === ''}>
            <DefaultStory />
          </Match>
          <For each={stories()}>
            {(component) => (
              <Match when={active() === component?.title}>
                {component.component}
              </Match>
            )}
          </For>
        </Switch>
      </section>
    </main>
  )
}

function DefaultStory() {
  return (
    <p class={styles.storybookSectionP}>
      The tiny storybook for{' '}
      <a
        href="https://docs.solidjs.com/"
        target="_blank"
        rel="norel noreferrer"
      >
        solid-js
      </a>
    </p>
  )
}

function Story(props) {
  // eslint-disable-next-line solid/reactivity
  const title = props.component?.title

  return (
    <Show when={title} fallback={props.component}>
      <div>
        <a
          href={`#${title}`}
          class={props.active() === title ? styles.active : ''}
        >
          {title}
        </a>
      </div>
    </Show>
  )
}

const cssUnit = (unit) => {
  const n = Number(unit)
  return !isNaN(n) ? `${n}px` : unit
}

// packages/svelte/src/Storybook.svelte
<script>
  import styles from './Storybook.module.css'
  import { onMount } from 'svelte'
  import Story from './Story.svelte'
  import DefaultStory from './DefaultStory.svelte'

  export let stories = []
  export let header = 'Storybook Tiny'
  export let href = '/stories/index.html'
  export let width = 130

  const cssUnit = (unit) => {
    const n = Number(unit)
    return isNaN(n) ? unit : `${n}px`
  }

  const getLocationHash = () =>
    decodeURIComponent(window.location.hash.slice(1))

  $: locHash = getLocationHash()

  onMount(() => {
    // define hash router
    const handleHashchange = () => {
      locHash = getLocationHash()
    }
    window.addEventListener('hashchange', handleHashchange)
    return () => {
      window.removeEventListener('hashchange', handleHashchange)
    }
  })

  let component = DefaultStory

  $: titles = stories.reduce((acc, story, id) => {
    switch (typeof story) {
      case 'object': {
        if (!story.component) {
          break
        }
        const title = story.title
        if (!title) {
          break
        }
        const active = locHash === title
        if (active) {
          component = story.component
        }
        acc.push({ id, title, active, href: `#${title}` })
        break
      }
      case 'string': {
        acc.push({ id, html: story })
        break
      }
    }
    return acc
  }, [])
</script>

<main class={styles.storybook}>
  <aside style={`flex-basis: ${cssUnit(width)}`}>
    <h4>
      <a {href}>
        {header}
      </a>
    </h4>
    {#each titles as title (title.id)}
      <Story {title} />
    {/each}
  </aside>
  <section class="stories">
    <svelte:component this={component} />
  </section>
</main>

<style>
</style>
