// packages/solid-js/stories/stories.jsx
import { render } from 'solid-js/web'
import Storybook from '../src/Storybook'
import { storyButton, storyWorks, storyAhrefNone } from './some.stories'

// define stories in storybook
render(
  () => (
    <Storybook
      stories={[
        <small>Components</small>,
        storyButton,
        storyWorks,
        storyAhrefNone
      ]} 
    />
  ),
  document.getElementById('app')
)

// packages/react/stories/stories.jsx
import React from 'react'
import ReactDOM from 'react-dom/client'
import Storybook from '../src/Storybook'
import { storyButton, storyError, storyAhrefNone, storyCounter } from './some.stories'

ReactDOM.createRoot(document.getElementById('app')).render(
  <React.StrictMode>
    <Storybook
      stories={[
        <small key="1">Components</small>,
        storyButton,
        storyAhrefNone,
        storyCounter,
        storyError,
      ]}
    />
  </React.StrictMode>
)
