// packages/solid-js/stories/stories.jsx
import { render } from 'solid-js/web'
import Storybook from '../src/Storybook'
import { storyButton, storyWorks, storyAhrefNone } from './some.stories'

// define stories in storybook
render(
  () => (
    <Storybook
      stories={[
        <small>Components</small>,
        storyButton,
        storyWorks,
        storyAhrefNone
      ]} 
    />
  ),
  document.getElementById('app')
)

// packages/preact/stories/stories.jsx
import { render } from 'preact'
import Storybook from '../src/Storybook'
import { storyButton, storyAhrefNone, storyError } from './some.stories'

// define stories in storybook
render(
  <Storybook
    stories={[
      <small key="1">Components</small>,
      storyButton,
      storyAhrefNone,
      storyError
    ]}
  />,
  document.getElementById('app')
)
