// packages/svelte/src/Storybook.svelte
<script>
  import styles from './Storybook.module.css'
  import { onMount } from 'svelte'
  import Story from './Story.svelte'
  import DefaultStory from './DefaultStory.svelte'

  export let stories = []
  export let header = 'Storybook Tiny'
  export let href = '/stories/index.html'
  export let width = 130

  const cssUnit = (unit) => {
    const n = Number(unit)
    return isNaN(n) ? unit : `${n}px`
  }

  const getLocationHash = () =>
    decodeURIComponent(window.location.hash.slice(1))

  $: locHash = getLocationHash()

  onMount(() => {
    // define hash router
    const handleHashchange = () => {
      locHash = getLocationHash()
    }
    window.addEventListener('hashchange', handleHashchange)
    return () => {
      window.removeEventListener('hashchange', handleHashchange)
    }
  })

  let component = DefaultStory

  $: titles = stories.reduce((acc, story, id) => {
    switch (typeof story) {
      case 'object': {
        if (!story.component) {
          break
        }
        const title = story.title
        if (!title) {
          break
        }
        const active = locHash === title
        if (active) {
          component = story.component
        }
        acc.push({ id, title, active, href: `#${title}` })
        break
      }
      case 'string': {
        acc.push({ id, html: story })
        break
      }
    }
    return acc
  }, [])
</script>

<main class={styles.storybook}>
  <aside style={`flex-basis: ${cssUnit(width)}`}>
    <h4>
      <a {href}>
        {header}
      </a>
    </h4>
    {#each titles as title (title.id)}
      <Story {title} />
    {/each}
  </aside>
  <section class="stories">
    <svelte:component this={component} />
  </section>
</main>

<style>
</style>

// packages/vue/src/Storybook.vue
<script setup>
import { ref, computed } from 'vue/dist/vue.esm-bundler.js'

const getLocHash = () => decodeURIComponent(window.location.hash.slice(1))

const cssUnit = (unit) => {
  const n = Number(unit)
  return isNaN(n) ? unit : `${n}px`
}

const props = defineProps({
  header: {
    type: String,
    default: 'Storybook Tiny'
  },
  href: {
    type: String,
    default: '/stories/index.html'
  },
  width: {
    type: [String, Number],
    default: 130
  },
  stories: {
    type: Array,
    default: () => []
  }
})

const width = cssUnit(props.width)
const stories = props.stories

const locHash = ref(getLocHash())
window.addEventListener('hashchange', () => {
  locHash.value = getLocHash()
})

let component = undefined
const titles = computed(() =>
  stories
    .map((story, i) => {
      switch (typeof story) {
        case 'object': {
          if ('component' in story) {
            const title = story.title ?? story.component?.__name
            if (!title) return
            const active = locHash.value === title
            if (active) {
              component = story.component
            }
            return {
              i,
              title,
              active,
              href: `#${title}`
            }
          }
        }
        case 'string': {
          return {
            i,
            html: story
          }
        }
      }
    })
    .filter(Boolean)
)
</script>

<template>
  <main :class="$style.storybook">
    <aside :style="{ flexBasis: width }">
      <h4>
        <a :href="props.href">
          {{ props.header }}
        </a>
      </h4>
      <div
        v-for="title in titles"
        :key="title.i"
      >
        <span
          v-if="title.html"
          v-html="title.html"
        />
        <a
          v-else
          :href="title.href"
          :class="[title.active ? $style.active : '']"
        >{{ title.title }}</a>
      </div>
    </aside>
    <section class="stories">
      <p
        v-if="!component"
        :class="$style.storybookSectionP"
      >
        The tiny storybook for
        <a
          href="https://vuejs.org/guide/"
          target="_blanc"
          rel="norel noreferrer"
        >
          Vue.js
        </a>
      </p>
      <component
        :is="component"
        v-else
      />
    </section>
  </main>
</template>

<style module>
@import './Storybook.module.css';
</style>
